# Uncomment this line to define a global platform for your project
# source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'

target "Cookalicious" do

pod 'AFNetworking', '~> 2.0'
pod 'AFNetworkActivityLogger', '~> 2.0'
pod 'CHTCollectionViewWaterfallLayout'
pod 'Facebook-iOS-SDK', '~> 3.0'
pod 'iCarousel', '~> 1.8'
pod 'JVFloatLabeledTextField', '~> 1.0'
pod 'PromiseKit'
pod 'PromiseKit-AFNetworking'


end

target "CookaliciousTests" do

pod 'AFNetworking', '~> 2.0'
pod 'AFNetworkActivityLogger', '~> 2.0'
pod 'CHTCollectionViewWaterfallLayout'
pod 'Facebook-iOS-SDK', '~> 3.0'
pod 'iCarousel', '~> 1.8'
pod 'JVFloatLabeledTextField', '~> 1.0'
pod 'PromiseKit'
pod 'PromiseKit-AFNetworking'

end

